### ISSUE TITLE
Don't use the grunt-contrib prefix

### ISSUE THREAD

**Issue by sindresorhus** [inossidabile/grunt-testem-mincer#19]
The `grunt-contrib` prefix is reserved for officially supported grunt tasks in the [grunt org](https://github.com/gruntjs/).

Please rename this task to not use the `contrib` word both here and on npm.

*(I'm on the [Grunt team](https://github.com/orgs/gruntjs/members))*

**Comment by tbranyen** [comment]
Also thought this was officially maintained.  Can it just be migrated to the GruntJS org?
