### ISSUE TITLE
rename plus removal of old name from npm broke the world...

### ISSUE THREAD

**Issue by designfrontier** [inossidabile/grunt-testem-mincer#33]
I am sure the reasons were good but it completely broke all of our test server immediately and then broke all of our new people to the project... and would have taken us all out of commission eventually.

Something to watch out for in the future...

**Comment by designfrontier** [comment]
deprecation might have been a kinder path to the users...

**Comment by inossidabile** [comment]
I didn't expect this type of plugin to be used in any kind of production dependencies so I believed dropping it would make ppl migrate faster. Grunt team that one day introduced the new naming rules was bothering me for damned ages with this... I'm sorry it affected you.
