### ISSUE TITLE
Project Rename?

### ISSUE THREAD

**Issue by joelzimmer** [inossidabile/grunt-testem-mincer#34]
Hi,

Did this project used to be called `grunt-contrib-testem`? If so, it is no longer registered in npm (https://www.npmjs.com/package/grunt-contrib-testem) which means that any projects that have a dependency on it can no longer install it from npm/package.json. I'd like to update dependencies, so if you could let me know, that'd be great. Thanks!

**Comment by inossidabile** [comment]
It used to be indeed. I removed it from NPM because of constant complaints from Grunt team. It's safe to just rename it in your dependencies.
