### ISSUE TITLE
404 for old npm registry name

### ISSUE THREAD

**Issue by Charizard** [inossidabile/grunt-testem-mincer#35]
Today when I did npm install on cloning `torii`, I got this error

```
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/grunt-contrib-testem
npm ERR! 404
npm ERR! 404 'grunt-contrib-testem' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'torii'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Looks like you have renamed the registry from `grunt-contrib-testem` to `grunt-testem-mincer`. But also deleted the old npm package named `grunt-contrib-testem` from npm.

**Comment by inossidabile** [comment]
Please get the master branch of `torii`. It has updated dependency. Since this is dev dependency that can't directly affect using `torii` or any other packages it has been decided to remove old name instead of deprecating it.

**Comment by Charizard** [comment]
Thanks for the reply :+1:
